<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="2" passed="0" failed="0" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-10-07T17:11:21 IST" name="Default suite" finished-at="2022-10-07T17:12:03 IST" duration-ms="41436">
    <groups>
      <group name="smoke">
        <method signature="LoginTest.correctemailtest()[pri:1, instance:Com.Sample.testcases.LoginTest@72a85671]" name="correctemailtest" class="Com.Sample.testcases.LoginTest"/>
      </group> <!-- smoke -->
    </groups>
    <test started-at="2022-10-07T17:11:21 IST" name="Default test" finished-at="2022-10-07T17:12:03 IST" duration-ms="41436">
      <class name="Com.Sample.testcases.LoginTest">
        <test-method is-config="true" signature="init()[pri:0, instance:Com.Sample.testcases.LoginTest@72a85671]" started-at="2022-10-07T17:11:21 IST" name="init" finished-at="2022-10-07T17:11:21 IST" duration-ms="139" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method is-config="true" signature="startTest(java.lang.reflect.Method)[pri:0, instance:Com.Sample.testcases.LoginTest@72a85671]" started-at="2022-10-07T17:11:21 IST" name="startTest" finished-at="2022-10-07T17:11:21 IST" duration-ms="6" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void Com.Sample.testcases.LoginTest.correctemailtest() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method is-config="true" signature="Setup()[pri:0, instance:Com.Sample.testcases.LoginTest@72a85671]" started-at="2022-10-07T17:11:21 IST" name="Setup" finished-at="2022-10-07T17:11:59 IST" duration-ms="37544" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Setup -->
        <test-method signature="correctemailtest()[pri:1, instance:Com.Sample.testcases.LoginTest@72a85671]" started-at="2022-10-07T17:11:59 IST" name="correctemailtest" finished-at="2022-10-07T17:12:02 IST" duration-ms="3646" status="SKIP">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping this exception]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping this exception
at Com.Sample.utilities.testdataexecution.toCheckExecutionRequired(testdataexecution.java:18)
at Com.Sample.testcases.LoginTest.correctemailtest(LoginTest.java:40)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- correctemailtest -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:Com.Sample.testcases.LoginTest@72a85671]" started-at="2022-10-07T17:12:02 IST" name="teardown" finished-at="2022-10-07T17:12:03 IST" duration-ms="197" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="reportFlush()[pri:0, instance:Com.Sample.testcases.LoginTest@72a85671]" started-at="2022-10-07T17:12:03 IST" name="reportFlush" finished-at="2022-10-07T17:12:03 IST" duration-ms="730" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportFlush -->
      </class> <!-- Com.Sample.testcases.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
